# Generated by Django 5.1 on 2024-08-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('phone', models.CharField(db_column='Phone', max_length=255)),
                ('address', models.CharField(db_column='Address', max_length=255)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
    ]
