# Generated by Django 5.1 on 2024-08-23 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='trackobg',
            field=models.ForeignKey(db_column='TrackID', null=True, on_delete=django.db.models.deletion.CASCADE, to='track.track'),
        ),
    ]
