# Generated by Django 5.1 on 2024-08-25 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('trackobj', models.ForeignKey(db_column='TrackID', null=True, on_delete=django.db.models.deletion.CASCADE, to='track.track')),
            ],
        ),
    ]
