# Generated by Django 5.1 on 2024-08-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trianee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='image',
            field=models.CharField(db_column='Image', max_length=255, null='True'),
            preserve_default='True',
        ),
    ]
