# Generated by Django 5.1 on 2024-08-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trianee', '0004_alter_trainee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='image',
            field=models.ImageField(blank='True', db_column='Image', null=True, upload_to='media/'),
        ),
    ]
